name: Latest blog post workflow
on:
  schedule:
    # Runs every day at 12
    - cron: '00 12 1-31 1-12 *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://opensourced.hashnode.dev/rss.xml, https://opensourced.hashnode.dev/sitemap.xml"
